spring: 
  profiles: 
    active: 
    - dev

---
server: 
  port: 7001

spring: 
  profiles: dev
  application:
    name: config-eureka-client

eureka: 
  instance: 
    hostname: eureka7001.com
  client: 
    register-with-eureka: false